---
- name: download tarball
  get_url:
    url: "{{ generic_unix_url }}"
    dest: /tmp/rabbit.tar.xz
    mode: '0755'

- name: Create unpack dir
  file:
    path: /tmp/rabbitmq
    state: directory
    mode: '0755'

- name: Extract tarball into /tmp/rabbitmq
  unarchive:
    remote_src: yes
    src: /tmp/rabbit.tar.xz
    dest: /tmp/rabbitmq

- name: Move extracted dir to target location
  shell: "cp -a /tmp/rabbitmq/*/* /rabbitmq"

- name: add sbin to path
  lineinfile: >
   dest=/etc/environment
   state=present
   backrefs=yes
   regexp='PATH=(["]*)((?!.*?/{{ sbin_dir }}).*?)(["]*)$'
   line="PATH=\1\2:{{ sbin_dir }}\3"

- name: make var/lib/rabbitmq/ directory
  file:
    path: /rabbitmq/var/lib/rabbitmq/
    state: directory
    recurse: yes
    # owner: ubuntu
    # group: ubuntu
    mode: 0775

- name: Set rabbitmq erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /rabbitmq/var/lib/rabbitmq/.erlang.cookie
    mode: 0400

- name: Set rabbitmq erlang cookie for root
  template:
    src: erlang.cookie.j2
    dest: /root/.erlang.cookie
    mode: 0400

- name: Set rabbitmq erlang cookie for ubuntu
  template:
    src: erlang.cookie.j2
    dest: /home/ubuntu/.erlang.cookie
    owner: ubuntu
    group: ubuntu
    mode: 0400

- name: Set configuration
  template:
    src: rabbitmq.conf.j2
    dest: /rabbitmq/etc/rabbitmq/rabbitmq.conf
    mode: 0400

- name: Start RabbitMQ
  command: /rabbitmq/sbin/rabbitmq-server start -detached

- name: Enable RabbitMQ Management plugin
  command: /rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_management
  retries: 3
  delay: 20
  register: result
  until: result.rc == 0

- name: Enable RabbitMQ top plugin
  command: /rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_top

- name: Enable RabbitMQ prometheus plugin
  command: /rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_prometheus

- name: Enable RabbitMQ Sharding plugin
  command: /rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_sharding

- name: Enable RabbitMQ Consistent Hash Exchange plugin
  command: /rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_consistent_hash_exchange
  
- name: Create benchmark user
  command: "/rabbitmq/sbin/rabbitmqctl add_user {{ rabbitmq_user.name }} {{ rabbitmq_user.password }}"

- name: Set adminstrator tag
  command: "/rabbitmq/sbin/rabbitmqctl set_user_tags {{ rabbitmq_user.name }} administrator"